OBJS = 01_hello_SDL.cpp
CC = g++
INCLUDE_FLAGS = -I/usr/include/SDL2
COMPILER_FLAGS = -w
LINKER_FLAGS = -lSDL2
OBJ_NAME = 01_hello_SDL
all: $(OBJS)
	$(CC) $(OBJS) $(COMPILER_FLAGS) $(INCLUDE_FLAGS) $(LINKER_FLAGS) -o $(OBJ_NAME)
